include $(APPDIR)/Make.defs
PROGNAME = k7emmc
PRIORITY = 100
STACKSIZE = 8192
MODULE = $(CONFIG_EXAMPLES_K7EMMC)
MAINSRC = k7emmc_main.c
CSRCS = sdhci_read.c sdhci_command.c sdhci_control.c emmc_init.c gpt_readonly.c
include $(APPDIR)/Application.mk
