"""Generate bounded, normalized Chinese provisioning prompts for K7.

The model runs only on the development PC.  The board receives immutable PCM
and therefore does not need to keep a VITS/ONNX session in its small system
heap while the online ASR recognizer is resident.
"""

import hashlib
import json
import shutil
import struct
import subprocess
import wave
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
OUT = HERE / "generated"
TTS = ROOT / "work-in-progress/parallel-voicelink-runtime/runtime/sherpa-onnx-v1.12.14-win-x64-shared/bin/sherpa-onnx-offline-tts.exe"
MODEL_DIR = ROOT.parent / "语音模块/openvela-voicelink/models/vits-icefall-zh-aishell3"

PROMPTS = {
    "wake": "设备还没有联网，请联网。",
    "speak": "请说话。",
    "start": "开始扫描网络。",
    "found": "扫描完成，以下是无线网络列表。",
    "network_1": "网络一。",
    "network_2": "网络二。",
    "network_3": "网络三。",
    "network_4": "网络四。",
    "network_5": "网络五。",
    "choose": "请说网络编号。",
    "selected": "请输入无线网络密码。",
    "confirm": "请确认密码。",
    "connecting": "正在连接。",
    "connected": "联网成功。",
    "failed": "联网失败，请重试。",
}

# Before networking there is no cloud TTS.  These short, immutable clips let
# the board spell arbitrary ASCII SSIDs while keeping the ASR model resident.
# Longest Chinese spellings are matched first by PromptAssetOutput.
SSID_TOKENS = {
    "ssid_upper": "大写",
    "ssid_a": "艾", "ssid_b": "比", "ssid_c": "西", "ssid_d": "迪",
    "ssid_e": "伊", "ssid_f": "艾夫", "ssid_g": "吉", "ssid_h": "艾尺",
    "ssid_i": "爱", "ssid_j": "杰", "ssid_k": "凯", "ssid_l": "艾勒",
    "ssid_m": "艾姆", "ssid_n": "恩", "ssid_o": "欧", "ssid_p": "皮",
    "ssid_q": "丘", "ssid_r": "阿尔", "ssid_s": "艾丝", "ssid_t": "踢",
    "ssid_u": "优", "ssid_v": "维", "ssid_w": "达不溜", "ssid_x": "艾克斯",
    "ssid_y": "歪", "ssid_z": "贼德",
    "ssid_0": "零", "ssid_1": "一", "ssid_2": "二", "ssid_3": "三",
    "ssid_4": "四", "ssid_5": "五", "ssid_6": "六", "ssid_7": "七",
    "ssid_8": "八", "ssid_9": "九",
    "ssid_underscore": "下划线", "ssid_dash": "横杠", "ssid_dot": "点",
    "ssid_space": "空格", "ssid_symbol": "符号",
    "ssid_nonascii": "中文名称网络",
}
PROMPTS.update(SSID_TOKENS)


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalize_wav(source, target):
    with wave.open(str(source), "rb") as src:
        channels = src.getnchannels()
        width = src.getsampwidth()
        rate = src.getframerate()
        frames = src.getnframes()
        raw = src.readframes(frames)
    if channels != 1 or width != 2 or rate not in (8000, 16000) or not frames:
        raise RuntimeError(
            "unexpected WAV format: channels=%s width=%s rate=%s frames=%s"
            % (channels, width, rate, frames)
        )
    samples = list(struct.unpack(f"<{frames}h", raw))
    source_rate = rate
    source_frames = frames
    if rate == 8000:
        upsampled = []
        for index, value in enumerate(samples):
            following = samples[index + 1] if index + 1 < len(samples) else value
            upsampled.extend((value, int((value + following) / 2)))
        samples = upsampled
        rate = 16000
        frames = len(samples)
    source_peak = max(abs(value) for value in samples)
    if source_peak < 1:
        raise RuntimeError("silent prompt")
    # The codec is already configured for 0 dB DAC attenuation.  Normalize the
    # source to 90% full scale so speech is loud without integer clipping.
    scale = (32767 * 0.90) / source_peak
    normalized = [max(-32768, min(32767, round(value * scale))) for value in samples]
    target.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(target), "wb") as dst:
        dst.setnchannels(1)
        dst.setsampwidth(2)
        dst.setframerate(rate)
        dst.writeframes(struct.pack(f"<{frames}h", *normalized))
    return {
        "frames": frames,
        "rate": rate,
        "source_rate": source_rate,
        "source_frames": source_frames,
        "source_peak": source_peak,
        "normalized_peak": max(abs(value) for value in normalized),
        "duration_seconds": round(frames / rate, 3),
    }


def emit_header(entries):
    header = OUT / "k7_prompt_assets_generated.hpp"
    with header.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by generate_prompt_assets.py; do not edit.\n")
        out.write("#pragma once\n#include <cstddef>\n#include <cstdint>\n\n")
        out.write("namespace k7_prompt_assets {\n")
        out.write("struct Asset { const char* key; const std::int16_t* pcm; std::size_t frames; };\n\n")
        for key, wav_path, metadata in entries:
            with wave.open(str(wav_path), "rb") as src:
                raw = src.readframes(src.getnframes())
            samples = struct.unpack(f"<{metadata['frames']}h", raw)
            out.write(f"alignas(4) inline constexpr std::int16_t pcm_{key}[] = {{\n")
            for offset in range(0, len(samples), 16):
                out.write("  " + ", ".join(str(value) for value in samples[offset:offset + 16]) + ",\n")
            out.write("};\n")
        out.write("\ninline constexpr Asset assets[] = {\n")
        for key, _wav_path, metadata in entries:
            out.write(f'  {{"{key}", pcm_{key}, {metadata["frames"]}}},\n')
        out.write("};\n}\n")


def main():
    if not TTS.is_file():
        raise FileNotFoundError(TTS)
    required = [MODEL_DIR / name for name in ("model.onnx", "tokens.txt", "lexicon.txt")]
    if not all(path.is_file() for path in required):
        raise FileNotFoundError("incomplete VITS model")
    if OUT.exists():
        shutil.rmtree(OUT)
    raw_dir = OUT / "raw"
    wav_dir = OUT / "wav"
    raw_dir.mkdir(parents=True)
    entries = []
    for key, text in PROMPTS.items():
        raw = raw_dir / f"{key}.wav"
        command = [
            str(TTS),
            f"--vits-model={MODEL_DIR / 'model.onnx'}",
            f"--vits-tokens={MODEL_DIR / 'tokens.txt'}",
            f"--vits-lexicon={MODEL_DIR / 'lexicon.txt'}",
            "--sid=21",
            "--vits-length-scale=0.82",
            "--tts-silence-scale=0.12",
            f"--output-filename={raw}",
            text,
        ]
        result = subprocess.run(
            command, cwd=str(HERE), stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, universal_newlines=True, timeout=180
        )
        if result.returncode:
            raise RuntimeError(f"TTS failed for {key}: {result.stderr}")
        normalized = wav_dir / f"{key}.wav"
        metadata = normalize_wav(raw, normalized)
        entries.append((key, normalized, metadata))
    emit_header(entries)
    manifest = {
        "generator": Path(__file__).name,
        "speaker_id": 21,
        "sample_rate": 16000,
        "target_peak_ratio": 0.90,
        "vits_length_scale": 0.82,
        "model_sha256": sha256(MODEL_DIR / "model.onnx"),
        "prompts": {
            key: {"text": PROMPTS[key], **metadata, "wav_sha256": sha256(wav_path)}
            for key, wav_path, metadata in entries
        },
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "prompts": len(entries),
        "seconds": round(sum(float(item[2]["duration_seconds"]) for item in entries), 3),
        "header_bytes": (OUT / "k7_prompt_assets_generated.hpp").stat().st_size,
        "manifest_sha256": sha256(OUT / "manifest.json"),
    }, indent=2))


if __name__ == "__main__":
    main()
