# Initial-cache candidate only; requires reviewed full NuttX platform integration.
set(onnxruntime_BUILD_SHARED_LIB OFF CACHE BOOL "")
set(onnxruntime_BUILD_UNIT_TESTS OFF CACHE BOOL "")
set(onnxruntime_ENABLE_PYTHON OFF CACHE BOOL "")
set(onnxruntime_ENABLE_TRAINING OFF CACHE BOOL "")
set(onnxruntime_ENABLE_TRAINING_APIS OFF CACHE BOOL "")
set(onnxruntime_ENABLE_TRAINING_OPS OFF CACHE BOOL "")
set(onnxruntime_USE_CUDA OFF CACHE BOOL "")
set(onnxruntime_USE_ROCM OFF CACHE BOOL "")
set(onnxruntime_USE_XNNPACK OFF CACHE BOOL "")
set(onnxruntime_USE_DNNL OFF CACHE BOOL "")
set(onnxruntime_USE_EXTENSIONS OFF CACHE BOOL "")
set(onnxruntime_MINIMAL_BUILD OFF CACHE BOOL "Need real ONNX format loading")
set(onnxruntime_DISABLE_EXCEPTIONS OFF CACHE BOOL "Full ONNX path")
set(onnxruntime_REDUCED_OPS_BUILD ON CACHE BOOL "Requires generated Add-only registration files")
set(onnxruntime_CROSS_COMPILING ON CACHE BOOL "")
set(onnxruntime_USE_FULL_PROTOBUF OFF CACHE BOOL "Upstream default lite")
