include $(APPDIR)/Make.defs
PROGNAME = k7neon
PRIORITY = 100
STACKSIZE = 8192
MODULE = $(CONFIG_EXAMPLES_K7NEON)
MAINSRC = k7neon_main.c
ASRCS = neon_hold.S
CFLAGS += -mgeneral-regs-only
include $(APPDIR)/Application.mk
