"""Freeze approved fixed prompt PCM from the existing LAN gateway into firmware."""
import hashlib,json,socket,struct
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
prompts=json.loads((ROOT/'host/whole_device/voice_prompts.zh-CN.json').read_text(encoding='utf-8'))
folder=ROOT/'app/k7agent/cloud/assets';folder.mkdir(exist_ok=True)
data=bytearray();records=[]
def exact(s,n):
 b=bytearray()
 while len(b)<n:
  chunk=s.recv(n-len(b))
  if not chunk:raise RuntimeError('incomplete_prompt')
  b.extend(chunk)
 return bytes(b)
for key,text in prompts.items():
 encoded=text.encode()
 with socket.create_connection(('10.3.1.125',8001),timeout=20) as s:
  s.settimeout(60);s.sendall(b'K7S1PT'+struct.pack('!I',len(encoded))+encoded)
  head=exact(s,5);size=struct.unpack('!I',head[1:])[0]
  assert head[:1]==b'D' and 0<size<=960000 and size%2==0
  pcm=exact(s,size)
 records.append(dict(key=key,text=text,offset=len(data),bytes=len(pcm),sha256=hashlib.sha256(pcm).hexdigest()))
 data.extend(pcm)
assert len(data)<=4*1024*1024
(folder/'fixed_prompts.pcm').write_bytes(data)
(folder/'fixed_prompts.json').write_text(json.dumps({'format':'s16le','rate':16000,'channels':1,'sha256':hashlib.sha256(data).hexdigest(),'prompts':records},ensure_ascii=False,indent=2),encoding='utf-8')
lines=['/* Generated by tools/freeze_board_prompts.py; immutable 16kHz mono PCM. */',
       'static const unsigned char k7_fixed_pcm[] __attribute__((aligned(2))) = {']
for start in range(0,len(data),32):lines.append(','.join(str(v) for v in data[start:start+32])+',')
lines+=['};','struct k7_fixed_prompt { const char *key; unsigned offset,bytes; };',
        'static const struct k7_fixed_prompt k7_fixed_prompts[] = {']
for row in records:lines.append('{"%s",%u,%u},'%(row['key'],row['offset'],row['bytes']))
lines+=['};']
(ROOT/'app/k7agent/cloud/src/board_fixed_pcm.inc').write_text('\n'.join(lines)+'\n',encoding='ascii')
print(json.dumps({'prompts':len(records),'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()}))
