"""Generate the board's fixed prompt-key table from the host source of truth."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
prompts = json.loads((ROOT/'host/whole_device/voice_prompts.zh-CN.json').read_text(encoding='utf8'))
lines = ['/* Generated by tools/generate_board_voice_prompts.py; UTF-8. */',
         'struct k7_prompt_entry { const char *key; const char *text; };',
         'static const struct k7_prompt_entry k7_voice_prompts[] = {']
for key, text in prompts.items():
    assert key.isascii() and len(text.encode('utf8')) <= 644
    lines.append('  {%s, %s},' % (json.dumps(key), json.dumps(text, ensure_ascii=False)))
lines += ['};', '']
(ROOT/'app/k7agent/cloud/src/board_voice_prompts.inc').write_text('\n'.join(lines),encoding='utf8')
print('Generated',len(prompts),'fixed voice prompts')
